apiVersion: v1
kind: Secret
metadata:
  name: storageos
  labels:
    app: storageos
type: Opaque
data:
  username: '{{repl ConfigOption "admin_username" | Base64Encode}}'
  password: '{{repl ConfigOption "admin_password" | Base64Encode}}'
  csiProvisionUsername: '{{repl ConfigOption "admin_password" | Base64Encode}}'
  csiProvisionPassword: '{{repl ConfigOption "admin_password" | Base64Encode}}'
  csiControllerPublishUsername: '{{repl ConfigOption "admin_password" | Base64Encode}}'
  csiControllerPublishPassword: '{{repl ConfigOption "admin_password" | Base64Encode}}'
  csiNodePublishUsername: '{{repl ConfigOption "admin_password" | Base64Encode}}'
  csiNodePublishPassword: '{{repl ConfigOption "admin_password" | Base64Encode}}'
  csiControllerExpandUsername: '{{repl ConfigOption "admin_password" | Base64Encode}}'
  csiControllerExpandPassword: '{{repl ConfigOption "admin_password" | Base64Encode}}'
