apiVersion: troubleshoot.replicated.com/v1beta1
kind: Preflight
metadata:
  name: storageos
spec:
  analyzers:
    - nodeResources:
        checkName: Cluster Node Count
        outcomes:
          - fail:
              when: "count() < 3"
              message: StorageOS Requires a least 3 nodes, with 5 recommended
              uri: https://kurl.sh/docs/install-with-kurl/adding-nodes
          - warn:
              when: "count() < 5"
              message: StorageOS Requires a least 3 nodes, with 5 recommended
              uri: https://kurl.sh/docs/install-with-kurl/adding-nodes
          - pass:
              message: This cluster has enough nodes
    - nodeResources:
        checkName: Cluster Memory
        outcomes:
          - fail:
              when: "sum(memoryAllocatable) < 10Gi"
              message: Sentry Requires 10Gi allocatable memory, with 32Gi recommended
              uri: https://kurl.sh/docs/install-with-kurl/system-requirements
          - warn:
              when: "sum(memoryAllocatable) < 32Gi"
              message: StorageOS Requires 10Gi allocatable memory, with 32Gi recommended
              uri: https://kurl.sh/docs/install-with-kurl/system-requirements
          - pass:
              message: Cluster has at least 32 Gi of memory
    - nodeResources:
        checkName: Cluster CPU
        outcomes:
          - fail:
              when: "sum(cpuCapacity) < 4"
              message: The cluster must contain at least 4 cores
              uri: https://kurl.sh/docs/install-with-kurl/system-requirements
          - pass:
              message: There are at least 4 cores in the cluster
    - nodeResources:
        checkName: Node Ephemeral Storage
        outcomes:
          - fail:
              when: "min(ephemeralStorageAllocatable) < 40Gi"
              message: StorageOS requires 40GB of allocatable ephemeral storage per node, (100GB recommended)
              uri: https://kurl.sh/docs/install-with-kurl/system-requirements
          - warn:
              when: "min(ephemeralStorageAllocatable) < 100Gi"
              message: StorageOS requires 40GB of allocatable ephemeral storage per node, (100GB recommended)
              uri: https://kurl.sh/docs/install-with-kurl/system-requirements
          - pass:
              message: All nodes have at least 100 GB of allocatable ephemeral storage
    - distribution:
        outcomes:
          - fail:
              when: "== docker-desktop"
              message: The application does not support Docker Desktop Clusters
          - fail:
              when: "== microk8s"
              message: The application does not support Microk8s Clusters
          - fail:
              when: "== minikube"
              message: The application does not support Minikube Clusters
          - pass:
              when: "== eks"
              message: EKS is a supported distribution
          - pass:
              when: "== gke"
              message: GKE is a supported distribution
          - pass:
              when: "== aks"
              message: AKS is a supported distribution
          - pass:
              when: "== kurl"
              message: KURL is a supported distribution
          - pass:
              when: "== digitalocean"
              message: DigitalOcean is a supported distribution
          - warn:
              message: Unable to determine the distribution of Kubernetes
    - clusterVersion:
        checkName: Kubernetes Version
        outcomes:
          - fail:
              when: "< 1.17.0"
              message: StorageOS requires at Kubernetes 1.17.0 or later
              uri: https://www.kubernetes.io
          - pass:
              when: ">= 1.17.0"
              message: Your cluster meets the recommended and required versions of Kubernetes
    - containerRuntime:
        checkName: Container Runtime
        outcomes:
          - pass:
              when: "== docker"
              message: Docker is a supported runtime
          - pass:
              when: "== containerd"
              message: ContainerD is a supported runtime
          - fail:
              message: StorageOS only supports docker and containerd as container runtimes
